#fail_fast: false
#repos:
#- repo: https://github.com/pocc/pre-commit-hooks
#  rev: v1.3.5
#  hooks:
#    - id: clang-format
#      args: [--style=Google, -i]
#    - id: cpplint
#  - repo: https://github.com/pre-commit/mirrors-prettier
#    rev: "v3.1.0"
#    hooks:
#      - id: prettier
